ALTER TABLE users ADD COLUMN token VARCHAR(64) UNIQUE;
ALTER TABLE evaluacion ADD COLUMN token VARCHAR(64);
ALTER TABLE evaluacion ADD COLUMN login_method VARCHAR(20);
ALTER TABLE evaluacion ADD COLUMN cod_nino NVARCHAR(50);
