version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]


  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: sa
      DB_PASSWORD: YourStrong@Passw0rd
      DB_NAME: protege

